<?php

use App\Model\Gig\UserGig;
use App\Model\Order\Order;
use App\User;
use Carbon\Carbon;
use Illuminate\Database\Seeder;

use Illuminate\Support\Str;

class OrderSeeder extends Seeder
{
	/**
	 * Run the database seeds.
	 *
	 * @return void
	 */
	public function run()
	{
		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 0";
		$order->order_description = "order 0 description.";
		$order->order_time = Carbon::now()->addDays(1);
		$order->order_time_in_days = 1;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 0 title.";
		$order->order_requirement_description = "order 0 description ok.";
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 1";
		$order->order_description = "order 1 description.";
		$order->order_time = Carbon::now()->addDays(1);
		$order->order_time_in_days = 1;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 1 title.";
		$order->order_requirement_description = "order 1 description ok.";
		$order->order_delivery_date = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'gig_package';
		$order->order_number = uniqid();
		$order->order_title = "order 2";
		$order->order_description = "order 2 description.";
		$order->order_time = Carbon::now()->addDays(2);
		$order->order_time_in_days = 2;
		$order->price = 100;
		$order->seller_earning = 80;
		$order->ask_for_requirements = true;
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->is_late = true;
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 4";
		$order->order_description = "order 4 description.";
		$order->order_time = Carbon::now()->addDays(112);
		$order->order_time_in_days = 112;
		$order->price = 5;
		$order->seller_earning = 4;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 3.";
		$order->order_requirement_description = "order 3 description";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->order_delivered_at = Carbon::now()->addDay();
		$order->revisions = 3;
		$order->status = 'completed';
		$order->is_cleared = true;
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 3;
		$order->order_source = 'gig_package';
		$order->order_number = uniqid();
		$order->order_title = "order 20";
		$order->order_description = "order 20 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order requirement title.";
		$order->order_requirement_description = "order requirement description ok.";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->order_delivered_at = Carbon::now();
		$order->order_cancelled_at = Carbon::now()->addDay();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'cancelled';
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 5 title";
		$order->order_description = "order 5 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = false;
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 6 title";
		$order->order_description = "order 6 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = true;
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'gig_package';
		$order->order_number = uniqid();
		$order->order_title = "order 11";
		$order->order_description = "order 11 description.";
		$order->order_time = Carbon::now()->addDays(2);
		$order->order_time_in_days = 2;
		$order->price = 100;
		$order->seller_earning = 80;
		$order->ask_for_requirements = true;
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'active';
		$order->is_late = true;
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 12";
		$order->order_description = "order 12 description.";
		$order->order_time = Carbon::now()->addDays(112);
		$order->order_time_in_days = 112;
		$order->price = 5;
		$order->seller_earning = 4;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 3.";
		$order->order_requirement_description = "order 3 description";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->order_delivered_at = Carbon::now()->addDay();
		$order->revisions = 3;
		$order->status = 'delivered';
		$order->is_cleared = false;
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 12";
		$order->order_description = "order 12 description.";
		$order->order_time = Carbon::now()->addDays(112);
		$order->order_time_in_days = 112;
		$order->price = 5;
		$order->seller_earning = 4;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 3.";
		$order->order_requirement_description = "order 3 description";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->order_delivered_at = Carbon::now()->addDay();
		$order->revisions = 3;
		$order->status = 'delivered';
		$order->is_cleared = false;
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 10";
		$order->order_description = "order 10 description.";
		$order->order_time = Carbon::now()->addDays(112);
		$order->order_time_in_days = 112;
		$order->price = 5;
		$order->seller_earning = 4;
		$order->ask_for_requirements = true;
		$order->order_requirement_title = "order 3.";
		$order->order_requirement_description = "order 3 description";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->order_delivered_at = Carbon::now()->addDay();
		$order->revisions = 3;
		$order->status = 'completed';
		$order->is_cleared = true;
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'gig_package';
		$order->order_number = uniqid();
		$order->order_title = "order 7 title";
		$order->order_description = "order 7 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = false;
		$order->order_delivery_date = Carbon::now();
		$order->order_delivered_at = Carbon::now();
		$order->order_cancelled_at = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'cancelled';
		$order->save();

		$order = new Order();
		$order->buyer_id = 4;
		$order->seller_id = 5;
		$order->gig_id = 2;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 8 title";
		$order->order_description = "order 8 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = true;
		$order->order_title = "order 8 title";
		$order->order_description = "order 8 description.";
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->order_delivered_at = Carbon::now();
		$order->order_cancelled_at = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'in_revision';
		$order->save();

		$order = new Order();
		$order->buyer_id = 5;
		$order->seller_id = 4;
		$order->gig_id = 1;
		$order->order_source = 'custom_offer';
		$order->order_number = uniqid();
		$order->order_title = "order 9 title";
		$order->order_description = "order 9 description.";
		$order->order_time = Carbon::now()->addDays(12);
		$order->order_time_in_days = 12;
		$order->price = 10;
		$order->seller_earning = 8;
		$order->ask_for_requirements = false;
		$order->order_rated_at = Carbon::now();
		$order->order_delivery_date = Carbon::now();
		$order->order_delivered_at = Carbon::now();
		$order->order_cancelled_at = Carbon::now();
		$order->requirements_submited_at = Carbon::now();
		$order->revisions = 3;
		$order->status = 'in_revision';
		$order->save();
	}
}
